# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.4.1
_src_path: https://github.com/trobz/trobz-python-template.git
author_email: contact@trobz.com
author_username: trobz
enable_docs_site: false
enable_github_action: true
package_name: odoo_activity
project_description: TUI tool named odoo-activity (inspired by pg_activity)
project_name: odoo-activity
project_type: cli
publish_to_pypi: false
repository_name: odoo-activity
repository_namespace: trobz
