# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.4.1
_src_path: https://github.com/trobz/trobz-python-template.git
author_email: contact@trobz.com
author_username: trobz
enable_docs_site: true
enable_github_action: true
package_name: odoo_activity
project_description: The odoo ops toolbox, for you (TUI) and your agent (MCP)
project_name: odoo-activity
project_type: cli
publish_to_pypi: true
repository_name: odoo-activity
repository_namespace: trobz
